name: Virginshr
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5386221220251173
title: Virgins отдел найма
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5216b'
    - '#31528c'
    - '#ffffff'
    - '#120d0e'
    - '#8c968f'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
